# Generated by Django 6.0.4 on 2026-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
