# Generated by Django 6.0.4 on 2026-10-07 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medicalrecord_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
